import NavBar from '@/components/navBar'
import './globals.css'
import type { Metadata } from 'next'
import { Catamaran, Cormorant_Garamond } from 'next/font/google'

const catamaran = Catamaran({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-catamaran'
})

const cormorant_garamond = Cormorant_Garamond({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-cormorant-garamond'
})



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${catamaran.variable} ${cormorant_garamond.variable} font-sans bg-primary text-primary`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
